# Generated by Django 5.0.5 on 2024-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_alter_user_instagram_id_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
