# Generated by Django 5.0.6 on 2024-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_user_created_time_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackUp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=20, unique=True)),
                ("age", models.IntegerField()),
                ("instagram_id", models.CharField(max_length=50, unique=True)),
                ("hobby", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
