# Generated by Django 5.0.6 on 2024-05-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0003_backup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BackUp",
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
