# Generated by Django 5.0.6 on 2024-05-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0005_alter_user_hobby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hobby",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
