# Generated by Django 5.0.6 on 2024-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_user_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(max_length=50),
        ),
    ]
