# Generated by Django 5.0.6 on 2024-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "all"), ("O", "opposite")], max_length=1
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
